<?php require '../header.php'; ?>
<?php require '../components/common/breadcrumbs.php'; ?>

<div class="container fj_content">
  <h1 class="h1">About FJewellery</h1>
  <p>We are a London based jewellers specializing in both new and pre-owned jewellery. Our collection includes all types of jewellery including beautiful pendants, a large variety of chains and bracelets as well as specially selected earrings and rings.</p>
  <p>At F Jewellery we know that jewellery is the most preferred gift for our loved ones, and we know that sometimes it is not easy to afford.</p>
  <p>We are sure you have heard stories about how someone got a ‘Great Deal’ because they had a ‘Friend from The Jewellery Trade’. F Jewellery is not a typical jewellery retailer, we consider ourselves as a ‘Window to the Trade’. We are working on a modest commission because we want you to buy the best for your loved ones. Let us be your ‘Friend from The Jewellery Trade’....</p>
  <p>We do a very careful selection of jewellery to make sure that our customers can find what they desire. However, at F Jewellery we know that sometimes you can't find the perfect piece, because you are looking for something very special. To help our customers with their special ideas, we work with the best UK suppliers and workshops. So, if you can't find anything or you have a special project in mind, please contact us and we will do our best to source or make the jewellery you desire.</p>
  <p>Our concierge services also include bespoke engagement rings. Please contact us and we will arrange a meeting with our jewellery specialist who will help you to design your bespoke ring step by step, starting from finding the right stone for you ending with a beautiful ring in our presentation box. </p>
  <p>Another area of our expertise is pre-owned jewellery. I think it is a much-discussed question of whether to buy pre-owned jewellery or not. For me, as an experienced jeweller, the answer is yes. Buying pre-owned jewellery is common practice in the UK, a large number of auction houses and thousands of jewellery items sold per month are best proofs of this. Buying pre-owned jewellery has two major advantages.</p>
  <p>First - buying pre-owned jewellery helps to save the planet. Pre-owned rings, earrings and other items of jewellery are ''Eco-Friendly''. I know this may sound strange but let me explain how. When you are buying a pre-owned diamond ring you are not creating demand for diamonds, you are not creating demand for gold. It works the same way as recycling. Let me demonstrate this with a help of simple logical chain: When you buy new diamond jewellery the shop contacts the supplier to order new one, the supplier calls to manufacturer and orders new one, the manufacturer calls to diamond dealer to order new diamonds, then the rough diamond dealer gets involved and at the end, the mining company gets involved. In contrast with this when you are buying pre-loved jewellery the retailer is not contacting the supplier but waits for the next customer to sell his/her item or buys it from auction houses. So, it is more like the customer to a customer rather than a customer to business with the retailer acting as an agent.</p>
  <p>Second- Pre-owned jewellery is less expensive, the difference in price can be up to two-three times. When you are buying pre-owned jewellery you are not paying for the labour cost, the previous owner has done it for you, also you pay less tax. The other positive impact when you are buying pre-owned jewellery is that you support the local economy.</p>
  <p>At F Jewellery we understand customers concerns about the condition of pre-owned jewellery that's why we do a careful examination of each item to ensure that all the jewellery we sell are in a good condition and will serve you for years. We also professionally clean and polish them before selling.</p>
  <div>To improve our collection of pre-owned jewellery, we buy from the public on a regular base. We know that selling your jewellery can be stressful, many places are offering to buy and it is not easy to compare them. Unlike others we do not offer cash for gold, we are not bullion dealers, we buy and sell jewellery. We appreciate the sentimental value of jewellery, so your jewellery will not be destroyed it will find a new home and it will be loved and enjoyed again. It is easy to sell your jewellery to us, you just need to follow simple steps:</div>
  <p>Step 1. Fill the form and give us as many details as you can, including pictures, receipts and valuations. This will help us to give you a more precise initial offer.<br>
          Step 2. We will get back to you with Initial offer.<br>
          Step 3. If you find our offer interesting we will arrange a meeting to examine the jewellery and finalize the offer.<br>
          Step 4. Accept the offer and choose the payment method.</p>
  <p>F Jewellery also offers consignment services. This means we can sell your jewellery on your behalf. It works the same way with only one difference, we will pay you when the item is sold, till that even though the jewellery will be with us it remains your property till it is sold. We will cover it with our insurance so you don't have to worry. Not paying you at the spot allows us to offer you a better price, so if you are not in a rush to sell your jewellery we strongly recommend to look into this option.</p>
  <p>To conclude I would like to thank you on behalf of F Jewellery for finding time to read this article. I hope you will enjoy your experience with us.</p>
  <p>Please do not hesitate to contact us if you have any questions.</p>
  <p>Yours faithfully,</p>
  <p>Andranik Zatikyan PJDip, DGA, Cert GA
  <div>Managing Director</div></p>
</div>

<?php require '../footer.php'; ?>
