<?php require '../header.php'; ?>
<?php require '../components/main/banner.php'; ?>
<?php includeComponent('main/carousel', 'carousel/last-watched'); ?>
<?php require '../components/main/discover.php'; ?>
<?php includeComponent('main/carousel', 'carousel/best'); ?>
<?php require '../components/main/collections.php'; ?>
<?php includeComponent('main/carousel', 'carousel/trend'); ?>
<?php require '../components/main/blog.php'; ?>
<?php require '../footer.php'; ?>
