import "../scss/card.scss";
import { initCommon } from "./common";
import { initWatchedCarousel } from "./sliders/watched";
import { initCardMediaSlider } from "./sliders/card-media";
import { initCardEvents } from "./pages/card";
import { initQuickView } from "./pages/catalog";
import { initReviewForm } from "./react/forms/review";
import { initJoinForm } from "./react/forms/join";
import { initSeoScroll } from "./scroll/seo-text";
import { initSeoToggle } from "./seo/seo";
import { initTooltips } from "./tooltip/tooltip";
import { initSizeGuideTrigger } from "./react/modals/card";
import { initAddToBasket } from "./basket/card";
import { initCompareEvents } from "./common/compare";
import { initWishEvents } from "./common/wishlist";
import { fetchViewedProducts } from "./common/viewed";

document.addEventListener("DOMContentLoaded", function () {
  initCommon();
  initWatchedCarousel();
  initCardMediaSlider();
  initCardEvents();
  initReviewForm();
  initQuickView();
  initJoinForm();
  initSeoScroll();
  initSeoToggle();
  initTooltips();
  initSizeGuideTrigger();
  initAddToBasket();
  initCompareEvents();
  initWishEvents();
  fetchViewedProducts();
});
